version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - "build-line:2025.3"
    commit-message:
      prefix: "deps(2025.3)"

  - package-ecosystem: gradle
    directory: "/pycharm-plugin-2026.1"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - "build-line:2026.1"
    commit-message:
      prefix: "deps(2026.1)"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
    commit-message:
      prefix: "ci"
